[package]
name = "classroom"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
indexmap = {version = "2.13.0", features = ["serde"]}
rust_xlsxwriter = "0.93.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
